inherit_from: .rubocop_todo.yml

require:
  - rubocop
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - Rakefile
    - node_modules/**/*
    - vendor/bundle/**/*
  RSpec:
    Patterns:
      - '_spec.rb$'

Metrics/LineLength:
  Max: 130
Metrics/ClassLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 10
Metrics/AbcSize:
  Max: 25

Rails/ApplicationRecord:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Whitelist:
    - touch
    - toggle!

RSpec/SubjectStub:
  Enabled: false
RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true
  Max: 15
RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Layout/AlignArray:
  Enabled: true
Layout/AlignHash:
  Enabled: true


